/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package r6_aplikacjeokienkowe.z3_BMI;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author RAPHAEL
 */
public class BMI extends javax.swing.JFrame {

    /** Creates new form BMI */
    public BMI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tytul = new javax.swing.JLabel();
        plec_label = new javax.swing.JLabel();
        jRadioButton_M = new javax.swing.JRadioButton();
        jRadioButton_K = new javax.swing.JRadioButton();
        masa_label = new javax.swing.JLabel();
        masa_field = new javax.swing.JTextField();
        kg = new javax.swing.JLabel();
        wzrost_label = new javax.swing.JLabel();
        wzrost_field = new javax.swing.JTextField();
        cm = new javax.swing.JLabel();
        BMI_label = new javax.swing.JLabel();
        BMI_field = new javax.swing.JTextField();
        opis_field = new javax.swing.JTextField();
        policz_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tytul.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        tytul.setText("BODY MASS INDEKS");

        plec_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plec_label.setText("P£EÆ");

        buttonGroup1.add(jRadioButton_M);
        jRadioButton_M.setSelected(true);
        jRadioButton_M.setText("M");
        jRadioButton_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_K);
        jRadioButton_K.setText("K");
        jRadioButton_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_KActionPerformed(evt);
            }
        });

        masa_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        masa_label.setText("MASA");

        kg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kg.setText("kg");

        wzrost_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wzrost_label.setText("WZROST");

        cm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cm.setText("cm");

        BMI_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BMI_label.setText("BMI:");

        BMI_field.setEditable(false);
        BMI_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMI_fieldActionPerformed(evt);
            }
        });

        opis_field.setEditable(false);
        opis_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        policz_button.setText("POLICZ");
        policz_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policz_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tytul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(masa_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(plec_label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_M, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton_K))
                                    .addComponent(masa_field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wzrost_label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BMI_label))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wzrost_field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BMI_field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(opis_field, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(policz_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tytul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plec_label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_M)
                    .addComponent(jRadioButton_K))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(masa_field)
                    .addComponent(kg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masa_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wzrost_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(wzrost_field, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(policz_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BMI_field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMI_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opis_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jRadioButton_MActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jRadioButton_KActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void policz_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try {
        double arg1 = wczytajParametr(masa_field.getText());
        double arg2 = wczytajParametr(wzrost_field.getText())/100;
        double wynik = arg1/Math.pow(arg2,2);
        
            BMI_field.setText("" + wynik);
            BMI_field.setText(String.valueOf(wynik));           
            BMI_field.setText(Double.toString(wynik));
            BMI_field.setText(String.format("%.2f", wynik));
            opis_field.setForeground(Color.RED);
            
            if (wynik <16){
                opis_field.setText("Wyg³odzenie");
            } else if (wynik >=16 && wynik <17) {
                    opis_field.setText("Wychudzenie (spowodowane czêsto przez anoreksjê lub inn¹ ciê¿k¹ chorobê)");
            } else if (wynik >=17 && wynik <18.5) {
                opis_field.setForeground(Color.YELLOW);
                    opis_field.setText("Niedowaga");
            } else if (wynik >=18.5 && wynik <25) {
                opis_field.setForeground(Color.GREEN);
                    opis_field.setText("Wartoœæ prawid³owa");
            } else if (wynik >=25 && wynik <30) {
                opis_field.setForeground(Color.YELLOW);
                    opis_field.setText("Nadwaga");
            } else if (wynik >=30 && wynik <35) {		 
                    opis_field.setText("I stopieñ oty³oœci"); 
                    
            } else if (wynik >=35 && wynik <40) {
                    opis_field.setText("II stopieñ oty³oœci (oty³oœæ kliniczna)");
            } else if (wynik >=40) {
                    opis_field.setText("III stopieñ oty³oœci (oty³oœæ skrajna)");
            } else opis_field.setText("Nie prawid³owa wartoœæ");
        
        //BMI_field.setText(masa_field.getText()+masa_field.getText());
        } catch (NumberFormatException numberFormatException) {
            BMI_field.setText("B³¹d!");
            BMI_field.setForeground(Color.RED);
            
            JOptionPane.showMessageDialog(
                    this,
                    "Nieporawne dane.",
                    "B³¹d",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }                                             

    private void BMI_fieldActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         
 private double wczytajParametr(String parametr) {
        parametr = parametr.replace(",", ".");
        return Double.parseDouble(parametr);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField BMI_field;
    private javax.swing.JLabel BMI_label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cm;
    private javax.swing.JRadioButton jRadioButton_K;
    private javax.swing.JRadioButton jRadioButton_M;
    private javax.swing.JLabel kg;
    private javax.swing.JTextField masa_field;
    private javax.swing.JLabel masa_label;
    private javax.swing.JTextField opis_field;
    private javax.swing.JLabel plec_label;
    private javax.swing.JButton policz_button;
    private javax.swing.JLabel tytul;
    private javax.swing.JTextField wzrost_field;
    private javax.swing.JLabel wzrost_label;
    // End of variables declaration                   

}
