/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package r6_aplikacjeOkienkowe.z2_konwerterJednostek;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author RAPHAEL
 */
public class KonwerterJednostek extends javax.swing.JFrame {

    /**
     * Creates new form KonwerterJednostek
     */
    public KonwerterJednostek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        tytul = new javax.swing.JLabel();
        dlugosc1_field = new javax.swing.JTextField();
        dlugosc1_box = new javax.swing.JComboBox<>();
        dlugosc_button = new javax.swing.JButton();
        dlugosc2_field = new javax.swing.JTextField();
        dlugosc2_box = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tytul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tytul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytul.setText("Konwerter jednostek");

        dlugosc1_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm", "m", "km", "Cale", "Stopy", "Mile" }));

        dlugosc_button.setText("POLICZ");
        dlugosc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlugosc_buttonActionPerformed(evt);
            }
        });

        dlugosc2_field.setEditable(false);
        dlugosc2_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlugosc2_fieldActionPerformed(evt);
            }
        });

        dlugosc2_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm", "m", "km", "Cale", "Stopy", "Mile" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tytul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dlugosc1_field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlugosc1_box, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlugosc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlugosc2_field, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlugosc2_box, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dlugosc_button, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(dlugosc2_field)
                    .addComponent(dlugosc2_box)
                    .addComponent(dlugosc1_field)
                    .addComponent(dlugosc1_box))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void dlugosc2_fieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void dlugosc_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try{
           double arg = wczytajParametr(dlugosc1_field.getText());
           String operacja1 = String.valueOf(dlugosc1_box.getSelectedItem());
           String operacja2 = String.valueOf(dlugosc2_box.getSelectedItem());
           Double wynik = (LogikaKonwertera.oblicz(operacja1)*arg) / LogikaKonwertera.oblicz(operacja2);
           
           dlugosc2_field.setText("" + wynik);
           dlugosc2_field.setText(String.valueOf(wynik));
           dlugosc2_field.setText(Double.toString(wynik));
            
        } catch (NumberFormatException numberFormatException) {
            dlugosc2_field.setText("B³¹d!");
            dlugosc2_field.setForeground(Color.RED);
            
            
            
            JOptionPane.showMessageDialog(
                    this,
                    "Nieporawne dane.",
                    "B³¹d",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }                                              
    private double wczytajParametr(String parametr) {
            parametr = parametr.replace(",", ".");
            return Double.parseDouble(parametr);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonwerterJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonwerterJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonwerterJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonwerterJednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonwerterJednostek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> dlugosc1_box;
    private javax.swing.JTextField dlugosc1_field;
    private javax.swing.JComboBox<String> dlugosc2_box;
    private javax.swing.JTextField dlugosc2_field;
    private javax.swing.JButton dlugosc_button;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel tytul;
    // End of variables declaration                   
}
