
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package r6_aplikacjeOkienkowe.z1_kosztPaliwa;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author RAPHAEL
 */
public class KosztPaliwa extends javax.swing.JFrame {

    /**
     * Creates new form KosztPaliwa
     */
    public KosztPaliwa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tytul = new javax.swing.JLabel();
        spalanie_label = new javax.swing.JLabel();
        cena_label = new javax.swing.JLabel();
        trasa_label = new javax.swing.JLabel();
        spalanie_field = new javax.swing.JTextField();
        cena_field = new javax.swing.JTextField();
        trasa_field = new javax.swing.JTextField();
        ilosc_slider = new javax.swing.JSlider();
        ilosc_label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lacznie_label = new javax.swing.JLabel();
        naOsobe_label = new javax.swing.JLabel();
        lacznie_field = new javax.swing.JTextField();
        policz_button = new javax.swing.JButton();
        naOsobe_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tytul.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        tytul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytul.setText("KOSZT PALIWA");

        spalanie_label.setText("SPALANIE   l/100km");

        cena_label.setText("CENA PALIWA   z³");

        trasa_label.setText("D£UGOŒÆ TRASY km");

        ilosc_slider.setMajorTickSpacing(1);
        ilosc_slider.setMaximum(12);
        ilosc_slider.setMinimum(1);
        ilosc_slider.setPaintLabels(true);
        ilosc_slider.setValue(1);

        ilosc_label.setText("ILOŒÆ OSÓB");

        lacznie_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lacznie_label.setText("£¥CZNIE:");

        naOsobe_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        naOsobe_label.setText("NA OSOBÊ:");

        lacznie_field.setEditable(false);
        lacznie_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lacznie_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lacznie_fieldActionPerformed(evt);
            }
        });

        policz_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        policz_button.setText("POLICZ");
        policz_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policz_buttonActionPerformed(evt);
            }
        });

        naOsobe_field.setEditable(false);
        naOsobe_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spalanie_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cena_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trasa_label, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(ilosc_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spalanie_field)
                            .addComponent(trasa_field, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cena_field)
                            .addComponent(ilosc_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lacznie_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(naOsobe_label, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lacznie_field)
                            .addComponent(naOsobe_field)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(policz_button, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(tytul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tytul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spalanie_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spalanie_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cena_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cena_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trasa_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trasa_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ilosc_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ilosc_slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(policz_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lacznie_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lacznie_field, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(naOsobe_field)
                    .addComponent(naOsobe_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void lacznie_fieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void policz_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try {
            double arg1 = wczytajParametr(spalanie_field.getText());
            double arg2 = wczytajParametr(cena_field.getText());
            double arg3 = wczytajParametr(trasa_field.getText());
            double arg4 = ilosc_slider.getValue();

            Double wynik = arg1 * arg2 * arg3 * 0.01;
            Double wynik2 = wynik / arg4;

            //lacznie_field.setText(wynik + " z³");
            //lacznie_field.setText(String.valueOf(wynik));
            //lacznie_field.setText(Double.toString(wynik)+ " z³");
            lacznie_field.setText(String.format("%.2f z³", wynik));

            naOsobe_field.setText(String.format("%.2f z³", wynik2));

    }                                             
catch (NumberFormatException numberFormatException) {
            lacznie_field.setText("B³¹d!");
            lacznie_field.setForeground(Color.RED);

            JOptionPane.showMessageDialog(
                    this,
                    "Nieporawne dane.",
                    "B³¹d",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KosztPaliwa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KosztPaliwa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KosztPaliwa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KosztPaliwa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KosztPaliwa().setVisible(true);
            }
        });
    }

    private double wczytajParametr(String parametr) {
        parametr = parametr.replace(",", ".");
        return Double.parseDouble(parametr);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField cena_field;
    private javax.swing.JLabel cena_label;
    private javax.swing.JLabel ilosc_label;
    private javax.swing.JSlider ilosc_slider;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lacznie_field;
    private javax.swing.JLabel lacznie_label;
    private javax.swing.JTextField naOsobe_field;
    private javax.swing.JLabel naOsobe_label;
    private javax.swing.JButton policz_button;
    private javax.swing.JTextField spalanie_field;
    private javax.swing.JLabel spalanie_label;
    private javax.swing.JTextField trasa_field;
    private javax.swing.JLabel trasa_label;
    private javax.swing.JLabel tytul;
    // End of variables declaration                   
}
