/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package r6_aplikacjeokienkowe.z5_przedszkole;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author RAPHAEL
 */
public class Przedszkole extends javax.swing.JFrame {

    /**
     * Creates new form Przedszkole
     */
    public Przedszkole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Tytul = new javax.swing.JLabel();
        pierwsze_label = new javax.swing.JLabel();
        pozostale_label = new javax.swing.JLabel();
        ilosc_label = new javax.swing.JLabel();
        pierwsze_field = new javax.swing.JTextField();
        pln1 = new javax.swing.JLabel();
        pln2 = new javax.swing.JLabel();
        pozostale_field = new javax.swing.JTextField();
        wylicz_button = new javax.swing.JButton();
        wylicz_field = new javax.swing.JTextField();
        ile_slider = new javax.swing.JSlider();
        pln3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tytul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tytul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tytul.setText("Przedszkole");

        pierwsze_label.setText("OP£ATA ZA PIERWSZE DZIECKO");

        pozostale_label.setText("OP£ATA ZA POZOSTA£E DZIECI");

        ilosc_label.setText("ILOŒÆ DZIECI");

        pierwsze_field.setText("300");

        pln1.setText("PLN");

        pln2.setText("PLN");

        pozostale_field.setText("200");

        wylicz_button.setText("WYLICZ OP£ATÊ");
        wylicz_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wylicz_buttonActionPerformed(evt);
            }
        });

        wylicz_field.setEditable(false);

        ile_slider.setMajorTickSpacing(1);
        ile_slider.setMaximum(20);
        ile_slider.setMinimum(1);
        ile_slider.setMinorTickSpacing(1);
        ile_slider.setPaintLabels(true);
        ile_slider.setPaintTicks(true);

        pln3.setText("PLN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wylicz_button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wylicz_field))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pierwsze_label, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pozostale_label, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pozostale_field)
                                            .addComponent(pierwsze_field))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pln1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pln2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pln3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ilosc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ile_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(pierwsze_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pierwsze_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pln1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pozostale_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pozostale_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pln2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ilosc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ile_slider, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wylicz_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wylicz_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pln3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>                        

    private void wylicz_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try {
            wylicz_field.setForeground(Color.MAGENTA);
            double pierwsze = wczytajParametr(pierwsze_field.getText());
            double pozostale = wczytajParametr(pozostale_field.getText());
            int dzieci = ile_slider.getValue() - 1;
            
            double wynik = pozostale*dzieci + pierwsze;

            wylicz_field.setText(String.format("%.2f z³", wynik));

        } catch (NumberFormatException numberFormatException) {

            wylicz_field.setText("B³¹d!");
            wylicz_field.setForeground(Color.RED);

            JOptionPane.showMessageDialog(
                    this,
                    "Nieporawne dane.",
                    "B³¹d",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private double wczytajParametr(String parametr) {
        parametr = parametr.replace(",", ".");
        return Double.parseDouble(parametr);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przedszkole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przedszkole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przedszkole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przedszkole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przedszkole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Tytul;
    private javax.swing.JSlider ile_slider;
    private javax.swing.JLabel ilosc_label;
    private javax.swing.JTextField pierwsze_field;
    private javax.swing.JLabel pierwsze_label;
    private javax.swing.JLabel pln1;
    private javax.swing.JLabel pln2;
    private javax.swing.JLabel pln3;
    private javax.swing.JTextField pozostale_field;
    private javax.swing.JLabel pozostale_label;
    private javax.swing.JButton wylicz_button;
    private javax.swing.JTextField wylicz_field;
    // End of variables declaration                   
}
